### PR TITLE
Fix LICENSE copyright example

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Review by tkolcon — CHANGES_REQUESTED** [review]
Should be "2020 Łukasiewicz-PIAP"

**Comment by pablogs9** [comment]
This PR is autogenerated because of the LICENSE file error talked about in the OFERA meeting today.

 Just modify it in a convenient way for PIAP or close it if the current status is ok.

**Comment by tkolcon** [comment]
OK, now I see :)

**Comment by ralph-lange** [comment]
See discussion at https://github.com/micro-ROS/mcb/pull/1.

**Review by tkolcon — APPROVED** [review]

**Pull request merged**
